<a href="https://colab.research.google.com/github/codebyharsh77/Python_nielit/blob/main/Assignment_s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 1

In [ ]:
name = "Harsh"
age  = 19
course="Btech cse"
print('name:',name,'|age:',age,'|course:',course)

name: Harsh |age: 19 |course: Btech cse


In [ ]:
#swap numbers
a=4
b=9
a,b = b,a
print(a)

print(b)

9
4


In [ ]:
#Arithmetic operator
a=5
b=6
print(a+b)

print(a-b)

print(a*b)

print(a/b)

print(a%b)

11
-1
30
0.8333333333333334
5


In [ ]:
#percentage

a=int(input("enter marks of math"))
b=int(input("enter marks of english"))
c=int(input("enter marks of science"))

percentage=(a+b+c)/300*100
print(percentage)


x=10
print("Initial value:",x)

x+=5
print("After +=5:",x)


x*=2
print("After *=2:",x)


x-=4
print("After -=4:",x)


x/=2
print("After /=2:",x)

enter marks of math98
enter marks of english89
enter marks of science90
92.33333333333333
Initial value: 10
After +=5: 15
After *=2: 30
After -=4: 26
After /=2: 13.0


In [ ]:

# relation operator
num1 = int (input("enter the first number:"))
num2 = int (input("enter the second number:"))
if num1 == num2:
    print("Both number are equal.")
elif num1 > num2:
    print("The first number is greater than the second number.")
else:
    print("The second number is greater than the first number.")

enter the first number:67
enter the second number:68
The second number is greater than the first number.


In [ ]:
# logical operator
is_raining = True
have_umbrella = False

if not is_raining or (is_raining and have_umbrella):
    print("you can go outside.")
else:
    print("you cannot go outside.")

you cannot go outside.


In [ ]:

#identity operator
list1 = [1,2,3]
list2 = [1,2,3]
print("list1==list2: ",list==list2)
print("list1 is list2: ",list is list2)
#list1==list2  : true because both have same content
#list1 is list2 : false because they are different memory

list1==list2:  False
list1 is list2:  False


In [ ]:
#bitwise operator
num1 = int(input("enter 1st number:"))
num2 = int(input("enter 2nd number:"))
bitwise_and = num1 & num2
bitwise_or = num1 | num2
bitwise_xor = num1 ^ num2
print("bitwise AND: ",bitwise_and)
print("bitwise OR:",bitwise_or)
print("bitwise XOR:",bitwise_xor)

enter 1st number:56
enter 2nd number:78
bitwise AND:  8
bitwise OR: 126
bitwise XOR: 118


In [ ]:
#typecasting
int_num = int(input("enter an interger:"))
float_num = float(input("enter a float:"))
print("type of int_num: ",type(int_num))
print("type of float_num: ",type(float_num))
sum_as_int = int(int_num + float_num)
print("sum as interger:",sum_as_int)

enter an interger:5
enter a float:6.6
type of int_num:  <class 'int'>
type of float_num:  <class 'float'>
sum as interger: 11


Assignment 2

In [ ]:
#WAP to print number 1 to 10 but stop loop when number reach9
for num in range(1,11):
    if num==9:
        break
    print(num)

In [ ]:
#WAP that keep asking the user enter number stop when the user enter negative number
while True:
    num=int(input("Enter number:"))
    if num<0:
        print("exit loop")
        break

Enter number:6
Enter number:-7
exit loop


In [ ]:
#WAP to find first even number in a list using a for loop and break
l=[5,9,3,4,17,22]
for num in l:
    if num%2==0:
        print('first even number:',num)
        break
    else:
        print('not found')

not found
not found
not found
first even number: 4


In [ ]:
#keep adding number onwards untill total sum exceed 25 print last sum and digit
n=0
for num in range(1,100):
    n+=num
    if num>25:
        print('final sum:',n)

        print('last number added:',num)
        break

final sum: 351
last number added: 26


In [ ]:
#keep asking the user to guess the password untill they guess admin123 use while and break
password='admin123'
max_attempts=5
attempt=0
while attempt<max_attempts:
    guess=input('Enter password')

    if guess==password:
        print('correct password')
        break
    else:
        attempt+=1
        print(f'incorrect password.{max_attempts-attempt}attempts left.')
if attempt==max_attempts:
    print('too many wrong attempts.')

Enter passwordYff
incorrect password.4attempts left.
Enter passwordadmin123
correct password


In [ ]:
#print multiple of 7 using while loop stop the value greater than 100
n=7
while n<=100:
    print(n)
    n+=7

7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [ ]:
#Give a number print each digit untill a zero is found
n=input('Enter a number')
for num in n:
    if num==0:
        break
    print(num)

Enter a number5
5


Assignment 3

In [ ]:
#1. Reverse the order of words in a sentence
def reverse_words(sentence):
    return ' '.join(sentence.split()[::-1])

# Example:
print(reverse_words("I love Python"))  # Output: "Python love I"

Python love I


In [ ]:
#2. Count consonants in a string
def count_consonants(s):
    vowels = set("aeiouAEIOU")
    return sum(1 for ch in s if ch.isalpha() and ch not in vowels)

# Example:
print(count_consonants("Hello World"))

7


In [ ]:
#3. Check if two strings are anagrams
from collections import Counter

def is_anagram(str1, str2):
    return "Anagram" if Counter(str1.lower()) == Counter(str2.lower()) else "Not Anagram"

# Examples:
print(is_anagram("Listen", "Silent"))
print(is_anagram("Hello", "World"))

Anagram
Not Anagram


In [ ]:


#4. First non-repeating character (case-sensitive)
def first_unique_char(s):
    from collections import Counter
    counts = Counter(s)
    for ch in s:
        if counts[ch] == 1:
            return ch
    return None

# Examples:
print(first_unique_char("swiss"))
print(first_unique_char("programming"))

w
p


In [ ]:


#5. Compress a string
def compress_string(s):
    if not s:
        return s
    compressed = []
    count = 1
    for i in range(1, len(s)):
        if s[i] == s[i - 1]:
            count += 1
        else:
            compressed.append(s[i - 1] + str(count))
            count = 1
    compressed.append(s[-1] + str(count))
    compressed_str = ''.join(compressed)
    return compressed_str if len(compressed_str) < len(s) else s

# Example:
print(compress_string("aaabbc"))

aaabbc


In [ ]:


#6. Longest palindromic substring
def longest_palindrome(s):
    def expand(l, r):
        while l >= 0 and r < len(s) and s[l] == s[r]:
            l -= 1
            r += 1
        return s[l+1:r]

    longest = ""
    for i in range(len(s)):
        for a, b in [(i, i), (i, i+1)]:
            temp = expand(a, b)
            if len(temp) > len(longest):
                longest = temp
    return longest

# Examples:
print(longest_palindrome("babad"))
print(longest_palindrome("cbbd"))

bab
bb


In [ ]:
#7. Valid parentheses/brackets/braces
def is_valid_sequence(s):
    stack = []
    mapping = {')': '(', '}': '{', ']': '['}
    for ch in s:
        if ch in mapping.values():
            stack.append(ch)
        elif ch in mapping:
            if not stack or stack[-1] != mapping[ch]:
                return "Invalid"
            stack.pop()
    return "Valid" if not stack else "Invalid"

# Examples:
print(is_valid_sequence("({[]})"))
print(is_valid_sequence("(]"))

Valid
Invalid


Assignment 4

In [ ]:
#1. Create a dictionary of 5 students and print keys and values
students = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "Diana": 90,
    "Evan": 88
}

print("Student Names:", list(students.keys()))
print("Student Marks:", list(students.values()))

Student Names: ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan']
Student Marks: [85, 92, 78, 90, 88]


In [ ]:
#2. Count the frequency of each character in a string
string = "dictionary"
frequency = {}

for char in string:
    frequency[char] = frequency.get(char, 0) + 1

print("Character Frequency:")
print(frequency)

Character Frequency:
{'d': 1, 'i': 2, 'c': 1, 't': 1, 'o': 1, 'n': 1, 'a': 1, 'r': 1, 'y': 1}


In [ ]:
#3. Find the name(s) of the oldest person(s)
ages = {
    "Alice": 25,
    "Bob": 32,
    "Charlie": 32,
    "Diana": 28
}

max_age = max(ages.values())
oldest = [name for name, age in ages.items() if age == max_age]

print("Oldest person(s):", oldest)

Oldest person(s): ['Bob', 'Charlie']


In [ ]:
#4. Merge two dictionaries
dict1 = {"a": 1, "b": 2}
dict2 = {"c": 3, "d": 4}

merged_dict = {**dict1, **dict2}
print("Merged Dictionary:", merged_dict)

Merged Dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
#5. Dictionary of numbers (1-10) and their squares
squares = {x: x**2 for x in range(1, 11)}
print("Number Squares:", squares)

Number Squares: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
#6. Invert a dictionary (keys become values and values become keys)
original = {'a': 1, 'b': 2, 'c': 3}
inverted = {v: k for k, v in original.items()}
print("Inverted Dictionary:", inverted)

Inverted Dictionary: {1: 'a', 2: 'b', 3: 'c'}


In [ ]:
#7. Calculate average marks for each student in a nested dictionary
students = {
    "Alice": {"Math": 85, "English": 78},
    "Bob": {"Math": 92, "English": 88},
    "Charlie": {"Math": 75, "English": 70}
}

for name, subjects in students.items():
    avg = sum(subjects.values()) / len(subjects)
    print(f"{name}'s Average Marks: {avg:.2f}")

Alice's Average Marks: 81.50
Bob's Average Marks: 90.00
Charlie's Average Marks: 72.50


In [ ]:

#8. Group words by their length using a dictionary
words = ["apple", "bat", "ball", "car", "python", "cat"]
grouped_words = {}

for word in words:
    length = len(word)
    grouped_words.setdefault(length, []).append(word)

print("Grouped Words by Length:")
print(grouped_words)

Grouped Words by Length:
{5: ['apple'], 3: ['bat', 'car', 'cat'], 4: ['ball'], 6: ['python']}


In [ ]:
#10. Convert list of (name, score) into dictionary and print average
score_list = [("Alice", 85), ("Bob", 78), ("Alice", 90), ("Bob", 82), ("Charlie", 70)]
scores = {}

for name, score in score_list:
    scores.setdefault(name, []).append(score)

for name, score_list in scores.items():
    average = sum(score_list) / len(score_list)
    print(f"{name}'s Average Score: {average:.2f}")

Alice's Average Score: 87.50
Bob's Average Score: 80.00
Charlie's Average Score: 70.00


Assignment 5

In [ ]:

#1.WAP to make a pyramid:

rows = 5
for i in range(rows):
    print(" " * (rows - i - 1) + "* " * (i + 1))

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [ ]:
#2. Create a simple menu-driven program using while loop:

while True:
    print("\nMenu:")
    print("1. Greet")
    print("2. Add two numbers")
    print("3. Exit")

    choice = input("Enter your choice: ")

    if choice == '1':
        print("Hello!")
    elif choice == '2':
        a = int(input("Enter first number: "))
        b = int(input("Enter second number: "))
        print("Sum is:", a + b)
    elif choice == '3':
        print("Exiting program.")
        break
    else:
        print("Invalid choice!")


Menu:
1. Greet
2. Add two numbers
3. Exit
Enter your choice: 1
Hello!

Menu:
1. Greet
2. Add two numbers
3. Exit
Enter your choice: 2
Enter first number: 3
Enter second number: 6
Sum is: 9

Menu:
1. Greet
2. Add two numbers
3. Exit
Enter your choice: 3
Exiting program.


In [ ]:

#3. Generate a pattern like:

rows = 3
for i in range(1, rows + 1):
    print(" " * (rows - i) + "* " * i)

  * 
 * * 
* * * 


In [ ]:

#4. Draw a square pattern like star:

size = 5
for i in range(size):
    print("* " * size)

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
#5.Draw a circular pattern like star (approximation using math):

import math

radius = 5
for i in range((radius * 2) + 1):
    for j in range((radius * 2) + 1):
        distance = math.sqrt((i - radius)**2 + (j - radius)**2)
        if distance < radius + 0.5 and distance > radius - 0.5:
            print("*", end="")
        else:
            print(" ", end="")
    print()

   *****   
  *     *  
 *       * 
*         *
*         *
*         *
*         *
*         *
 *       * 
  *     *  
   *****   


In [ ]:
#6. Draw a rectangular pattern like star:

rows = 4
cols = 7
for i in range(rows):
    print("* " * cols)

* * * * * * * 
* * * * * * * 
* * * * * * * 
* * * * * * * 


In [ ]:
#7.Create a list of even numbers belonging to 5’s power:

lst = [i**2 for i in range(8) if i % 2 == 0]
print(lst)

[0, 4, 16, 36]


Assignment 6

In [ ]:
#1. Create a tuple with different data types and print its type:

my_tuple = (10, "Hello", 3.14, True)
print(my_tuple)
print(type(my_tuple))

(10, 'Hello', 3.14, True)
<class 'tuple'>


In [ ]:
#2. Access the second last element from the tuple:

t = (10, 20, 30, 40, 50)
print("Second last element:", t[-2])

Second last element: 40


In [ ]:
#3. Count the number of times an element appears in a tuple:

t = (1, 2, 3, 2, 4, 2, 5)
element = 2
print(f"{element} appears {t.count(element)} times")

2 appears 3 times


In [ ]:
#4. Convert a tuple of strings into a single string:

words = ('Python', 'is', 'fun')
sentence = ' '.join(words)
print(sentence)

Python is fun


In [ ]:
#5. Find the index of an element in a tuple:

t = (1, 2, 3, 4, 5)
element = 3
print(f"Index of {element} is {t.index(element)}")

Index of 3 is 2


In [ ]:
#6. Create two sets and perform union, intersection, and difference:

set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
print("Union:", set1 | set2)
print("Intersection:", set1 & set2)
print("Difference (set1 - set2):", set1 - set2)

Union: {1, 2, 3, 4, 5, 6}
Intersection: {3, 4}
Difference (set1 - set2): {1, 2}


In [ ]:
#7. Check if an element is present in a set or not:

s = {10, 20, 30}
element = 20
print(f"{element} is in set: {element in s}")

20 is in set: True


In [ ]:
#8. Remove duplicate elements from a list using a set:

my_list = [1, 2, 2, 3, 4, 4, 5]
unique_list = list(set(my_list))
print("List after removing duplicates:", unique_list)

List after removing duplicates: [1, 2, 3, 4, 5]


In [ ]:
#9. Find the symmetric difference between two sets:

set1 = {1, 2, 3}
set2 = {3, 4, 5}
print("Symmetric Difference:", set1 ^ set2)

Symmetric Difference: {1, 2, 4, 5}


In [ ]:
#10. Find all unique elements from a list using sets:

numbers = [1, 2, 2, 3, 4, 4, 5]
unique_elements = set(numbers)
print("Unique elements:", unique_elements)

Unique elements: {1, 2, 3, 4, 5}


Assignment 7

In [ ]:
#1. Write a function to find the factorial of a number using recursion.
def fact(n):
   if n < 0:
       return "Factorial is not defined for negative numbers"
   elif n == 0 or n == 1:
       return 1
   else:
       result = 1
       for i in range(2, n + 1):
           result *= i
       return result
print(fact(9))

362880


In [ ]:
#2. Write a function that checks whether a number is prime or not.
def is_prime(n):
   if n <= 1:
       return False
   for i in range(2, int(n**0.5) + 1):
       if n % i == 0:
           return False
   return True
print(is_prime(7))

True


In [ ]:
#3. Create a function that takes a string as input and returns the number of vowels in it.
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count
print(count_vowels("Hello! HARSH"))

3


In [ ]:
# 4. Write a function that accepts a list of numbers and returns the maximum and minimum values.
def find_max_min(numbers):
   if not numbers:
       return None
   max_num = min_num = numbers[0]
   for num in numbers:
       if num > max_num:
           max_num = num
       if num < min_num:
           min_num = num
   return max_num, min_num
print(find_max_min([3, 1, 4, 1, 5, 9, 2, 6]))

(9, 1)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#5. Write a Python function to calculate the nth Fibonacci number using recursion.
def fibonacci(n):
   if n <= 0:
      return []
   elif n == 1:
       return [0]
   elif n == 2:
       return [0, 1]

   fib_series = [0, 1]
   for i in range(2, n):
       next_value = fib_series[i - 1] + fib_series[i - 2]
       fib_series.append(next_value)
   return fib_series
n= int(input("Enter no: "))
print(fibonacci(n))

Enter no: 5
[0, 1, 1, 2, 3]


In [ ]:

#Create a function that accept two numbers and return GCD
import math
def find_gcd(a, b):
    return math.gcd(a, b)
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("The GCD is:", find_gcd(num1,num2))

Enter first number: 5
Enter second number: 6
The GCD is: 1


In [ ]:
#7. Write a function that takes a list and returns a new list with only unique elements.
def unique_elements(lst):
    unique_set = set(lst)
    return list(unique_set)

my_list = [1, 2, 2, 3, 4, 4, 5]
print(unique_elements(my_list))

[1, 2, 3, 4, 5]


In [ ]:
#9. Write a function that takes a number and returns True if it is a palindrome, otherwise False.
def is_palindrome(n):
   str_n = str(n)
   return str_n == str_n[::-1]
n=int(input("Enter No.: "))
print(is_palindrome(n))

In [ ]:
# 10. Create a function that takes a temperature in Celsius and returns it in Fahrenheit
#formulaa: c/5=(f-32)/9
def f_to_c(f):
    return 5*(f-32)/9
f=int(input("Enter tempreature:"))
c=f_to_c(f)
print(f"{round(c,3)}, degree celsisus")

#method 2
def celsius_to_fahrenheit(celsius):
   return (celsius * 9/5) + 32
celsisus= int(input("Enter tempreature:"))
print(celsius_to_fahrenheit(celsisus))

In [ ]:
# WAP to create a numpyarray with values 1 to 10
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr)
print("shape:",arr.shape)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)

Array: [ 1  2  3  4  5  6  7  8  9 10]
shape: (10,)
dimension: 1
data type: int64


In [ ]:
# WAP to create a 3x3 numpy array of all zeros and ones. then create a 3x3 identity maatrix
arrofzeros=np.zeros((3,3))
arrofones=np.ones((3,3))
identity_matrix=np.eye(3,k=0)
print(arrofzeros,arrofones,identity_matrix,sep="\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#WAP to generate an array of 15 random integers between 10 and 100 using random.randint
# random.randint(low,high=None,size=None,dtype=int)
arr=np.random.randint(10,100,15)
print(arr)
print(np.info(arr))
newarr=arr.reshape(3,5)
print(newarr)

[43 29 20 54 52 71 18 98 10 68 53 55 98 82 97]
class:  ndarray
shape:  (15,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x3e949970
byteorder:  little
byteswap:  False
type: int64
None
[[43 29 20 54 52]
 [71 18 98 10 68]
 [53 55 98 82 97]]


In [ ]:
#WAP to create a numpy array from 1 to 20, and extract every 3rd element starting from index 1 using slicing
arr=np.arange(1,21,1)
newarr=arr[0::3]
print(newarr)

[ 1  4  7 10 13 16 19]


In [ ]:
# WAP to create two arrays and perform operations on them.

import numpy as np

a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
c = np.array([])

for i in range(len(a)):
    c = np.append(c, a[i] + b[i])

print(c)

[ 3.  7. 11. 15.]


In [ ]:
# WAP to create a numpy array with 20 random values (0 to 1) using np.random.rand() and find the mean,median,standard deviation, min and max.

import numpy as np
arr=np.random.rand(20)
print(arr)

[0.97395637 0.69843283 0.05551456 0.13149149 0.77884279 0.93898319
 0.20447877 0.9829911  0.56619205 0.20718706 0.0071977  0.50858492
 0.42746946 0.99221259 0.4965154  0.87963706 0.76058012 0.11833936
 0.91706965 0.20117277]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D



+# Define the 3D array
array = np.array([[[1, 2, 3], [4,5,6]],[[1,2,3],[4,5,6]]])


# Get the shape of the array
depth, rows, cols = array.shape

# Create a 3D grid of coordinates
x, y, z = np.meshgrid(np.arange(cols), np.arange(rows), np.arange(depth), indexing='ij')

# Flatten the coordinates and array values
x_flat = x.flatten()
y_flat = y.flatten()
z_flat = z.flatten()
values = array.flatten()

# Plotting
fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with color mapping based on values
sc = ax.scatter(x_flat, y_flat, z_flat, c=values, cmap='viridis', s=100)

# Annotate each point with its value
for xi, yi, zi, val in zip(x_flat, y_flat, z_flat, values):
    ax.text(xi, yi, zi, f'{val}', color='black', fontsize=8, ha='center', va='center')

# Label axes
ax.set_xlabel('Column (X)')
ax.set_ylabel('Row (Y)')
ax.set_zlabel('Depth (Z)')

plt.title('3D Visualization of 3D Array')
plt.colorbar(sc, label='Value Intensity')
plt.tight_layout()
plt.show()

SyntaxError: invalid syntax (ipython-input-9-3528611096.py, line 7)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/diamonds.csv')
print('furst 10 rows')
print(df.head(10))

furst 10 rows
   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39


In [ ]:

# 2. Check the shape and column names of the dataset
print("\nShape:", df.shape)
print("Columns:", df.columns.tolist())


Shape: (50000, 12)
Columns: ['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z', 'price_updated', 'volume']


In [ ]:
# 3. Fill missing numeric values with their column means
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].apply(lambda col: col.fillna(col.mean()))

In [ ]:
# 4. Filter rows where 'cut' is "Ideal" and 'color' is "E"
filtered_df = df[(df['cut'] == 'Ideal') & (df['color'] == 'E')]
print("\nFiltered rows (cut='Ideal' and color='E'):")
print(filtered_df.head())


Filtered rows (cut='Ideal' and color='E'):
     carat    cut color clarity  depth  table  price     x     y     z
0     0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
76    0.26  Ideal     E    VVS2   62.9   58.0    554  4.02  4.06  2.54
82    0.70  Ideal     E     SI1   62.5   57.0   2757  5.70  5.72  3.57
100   0.59  Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35
102   0.74  Ideal     E     SI2   62.2   56.0   2761  5.80  5.84  3.62


In [ ]:
# 5. Group by 'cut' and compute average 'price'
avg_price_by_cut = df.groupby('cut')['price'].mean()
print("\nAverage price by cut:")
print(avg_price_by_cut)


Average price by cut:
cut
Fair         4329.705017
Good         3961.470266
Ideal        3463.090230
Premium      4607.382867
Very Good    3986.585594
Name: price, dtype: float64


In [ ]:
# 6. Sort by 'carat' in descending order and show top 5 rows
sorted_df = df.sort_values(by='carat', ascending=False)
print("\nTop 5 rows sorted by 'carat':")
print(sorted_df.head())


Top 5 rows sorted by 'carat':
       carat      cut color clarity  depth  table  price      x      y     z
25426   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
25624   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
25163   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
24102   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
24103   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24


In [ ]:
# 7. Convert 'price' to NumPy array and find mean, median, std
price_array = df['price'].values
print("\nPrice stats:")
print("Mean:", np.mean(price_array))
print("Median:", np.median(price_array))
print("Standard Deviation:", np.std(price_array))


Price stats:
Mean: 3944.80544
Median: 2410.0
Standard Deviation: 3997.8981250585175


In [ ]:
# 8. Count diamonds with 'price' > 5000 and 'carat' > 1
count = np.sum((df['price'] > 5000) & (df['carat'] > 1))
print("\nDiamonds with price > 5000 and carat > 1:", count)


Diamonds with price > 5000 and carat > 1: 12798


In [ ]:
# 9. Create 'price_updated' column by increasing price by 10%
df['price_updated'] = df['price'] * 1.10
print("\nUpdated price sample:")
print(df[['price', 'price_updated']].head())


Updated price sample:
   price  price_updated
0    326          358.6
1    326          358.6
2    327          359.7
3    334          367.4
4    335          368.5


In [ ]:
# 10. Create 'volume' column as x * y * z and find avg price where volume > 50
df['volume'] = df['x'] * df['y'] * df['z']
avg_price_vol = df[df['volume'] > 50]['price'].mean()
print("\nAverage price where volume > 50:", avg_price_vol)

NameError: name 'df' is not defined

In [ ]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score

In [ ]:
iris = pd.read_csv('/Iris.csv')
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
# check null values
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
iris.shape

(150, 6)

In [ ]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
# split into features and target variables
# X = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
# y = iris['Species']
X = iris.loc[:, ['SepalLengthCm','SepalWidthCm','PetalLengthCm', 'PetalWidthCm']]
#X = iris.iloc[:, 1:-1]
#Y= iris.iloc[:,-1]

In [ ]:
# fit model in x and y variable
model = LogisticRegression()
model.fit(X, Y)

LogisticRegression()

In [ ]:
# predict species of flower of samples 4.9 , 3.0, 1.4, 0.2
X = [[6, 3.0, 2, 5],[5.1,3.5,1.4,0.2]]
result = model.predict(X)
print(result)

['Iris-virginica' 'Iris-setosa']


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
# model accuracy
model.score(X, Y)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


ValueError: Found input variables with inconsistent numbers of samples: [150, 2]